// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/grpc/proto/booking.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_api_grpc_proto_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_booking_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBookingsRequest) Reset() {
	*x = GetUserBookingsRequest{}
	mi := &file_api_grpc_proto_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBookingsRequest) ProtoMessage() {}

func (x *GetUserBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBookingsRequest.ProtoReflect.Descriptor instead.
func (*GetUserBookingsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_booking_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserBookingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserBookingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserBookingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetUserBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	Meta          *PaginationMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBookingsResponse) Reset() {
	*x = GetUserBookingsResponse{}
	mi := &file_api_grpc_proto_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBookingsResponse) ProtoMessage() {}

func (x *GetUserBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBookingsResponse.ProtoReflect.Descriptor instead.
func (*GetUserBookingsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_booking_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *GetUserBookingsResponse) GetMeta() *PaginationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type BookTicketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConcertId     int64                  `protobuf:"varint,1,opt,name=concert_id,json=concertId,proto3" json:"concert_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TicketCount   int32                  `protobuf:"varint,3,opt,name=ticket_count,json=ticketCount,proto3" json:"ticket_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookTicketsRequest) Reset() {
	*x = BookTicketsRequest{}
	mi := &file_api_grpc_proto_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookTicketsRequest) ProtoMessage() {}

func (x *BookTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookTicketsRequest.ProtoReflect.Descriptor instead.
func (*BookTicketsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_booking_proto_rawDescGZIP(), []int{3}
}

func (x *BookTicketsRequest) GetConcertId() int64 {
	if x != nil {
		return x.ConcertId
	}
	return 0
}

func (x *BookTicketsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookTicketsRequest) GetTicketCount() int32 {
	if x != nil {
		return x.TicketCount
	}
	return 0
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_api_grpc_proto_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_booking_proto_rawDescGZIP(), []int{4}
}

func (x *CancelBookingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CancelBookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_api_grpc_proto_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_booking_proto_rawDescGZIP(), []int{5}
}

func (x *CancelBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConcertId     int64                  `protobuf:"varint,2,opt,name=concert_id,json=concertId,proto3" json:"concert_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TicketCount   int32                  `protobuf:"varint,4,opt,name=ticket_count,json=ticketCount,proto3" json:"ticket_count,omitempty"`
	BookingTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=booking_time,json=bookingTime,proto3" json:"booking_time,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_api_grpc_proto_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_booking_proto_rawDescGZIP(), []int{6}
}

func (x *Booking) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Booking) GetConcertId() int64 {
	if x != nil {
		return x.ConcertId
	}
	return 0
}

func (x *Booking) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Booking) GetTicketCount() int32 {
	if x != nil {
		return x.TicketCount
	}
	return 0
}

func (x *Booking) GetBookingTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BookingTime
	}
	return nil
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Booking) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Booking) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_grpc_proto_booking_proto protoreflect.FileDescriptor

const file_api_grpc_proto_booking_proto_rawDesc = "" +
	"\n" +
	"\x1capi/grpc/proto/booking.proto\x12\abooking\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bapi/grpc/proto/common.proto\"#\n" +
	"\x11GetBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"b\n" +
	"\x16GetUserBookingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"s\n" +
	"\x17GetUserBookingsResponse\x12,\n" +
	"\bbookings\x18\x01 \x03(\v2\x10.booking.BookingR\bbookings\x12*\n" +
	"\x04meta\x18\x02 \x01(\v2\x16.common.PaginationMetaR\x04meta\"o\n" +
	"\x12BookTicketsRequest\x12\x1d\n" +
	"\n" +
	"concert_id\x18\x01 \x01(\x03R\tconcertId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fticket_count\x18\x03 \x01(\x05R\vticketCount\"?\n" +
	"\x14CancelBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"1\n" +
	"\x15CancelBookingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xc1\x02\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"concert_id\x18\x02 \x01(\x03R\tconcertId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12!\n" +
	"\fticket_count\x18\x04 \x01(\x05R\vticketCount\x12=\n" +
	"\fbooking_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vbookingTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xb0\x02\n" +
	"\x0eBookingService\x12:\n" +
	"\n" +
	"GetBooking\x12\x1a.booking.GetBookingRequest\x1a\x10.booking.Booking\x12T\n" +
	"\x0fGetUserBookings\x12\x1f.booking.GetUserBookingsRequest\x1a .booking.GetUserBookingsResponse\x12<\n" +
	"\vBookTickets\x12\x1b.booking.BookTicketsRequest\x1a\x10.booking.Booking\x12N\n" +
	"\rCancelBooking\x12\x1d.booking.CancelBookingRequest\x1a\x1e.booking.CancelBookingResponseB#Z!concert-ticket-api/api/grpc/protob\x06proto3"

var (
	file_api_grpc_proto_booking_proto_rawDescOnce sync.Once
	file_api_grpc_proto_booking_proto_rawDescData []byte
)

func file_api_grpc_proto_booking_proto_rawDescGZIP() []byte {
	file_api_grpc_proto_booking_proto_rawDescOnce.Do(func() {
		file_api_grpc_proto_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_proto_booking_proto_rawDesc), len(file_api_grpc_proto_booking_proto_rawDesc)))
	})
	return file_api_grpc_proto_booking_proto_rawDescData
}

var file_api_grpc_proto_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_grpc_proto_booking_proto_goTypes = []any{
	(*GetBookingRequest)(nil),       // 0: booking.GetBookingRequest
	(*GetUserBookingsRequest)(nil),  // 1: booking.GetUserBookingsRequest
	(*GetUserBookingsResponse)(nil), // 2: booking.GetUserBookingsResponse
	(*BookTicketsRequest)(nil),      // 3: booking.BookTicketsRequest
	(*CancelBookingRequest)(nil),    // 4: booking.CancelBookingRequest
	(*CancelBookingResponse)(nil),   // 5: booking.CancelBookingResponse
	(*Booking)(nil),                 // 6: booking.Booking
	(*PaginationMeta)(nil),          // 7: common.PaginationMeta
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
}
var file_api_grpc_proto_booking_proto_depIdxs = []int32{
	6, // 0: booking.GetUserBookingsResponse.bookings:type_name -> booking.Booking
	7, // 1: booking.GetUserBookingsResponse.meta:type_name -> common.PaginationMeta
	8, // 2: booking.Booking.booking_time:type_name -> google.protobuf.Timestamp
	8, // 3: booking.Booking.created_at:type_name -> google.protobuf.Timestamp
	8, // 4: booking.Booking.updated_at:type_name -> google.protobuf.Timestamp
	0, // 5: booking.BookingService.GetBooking:input_type -> booking.GetBookingRequest
	1, // 6: booking.BookingService.GetUserBookings:input_type -> booking.GetUserBookingsRequest
	3, // 7: booking.BookingService.BookTickets:input_type -> booking.BookTicketsRequest
	4, // 8: booking.BookingService.CancelBooking:input_type -> booking.CancelBookingRequest
	6, // 9: booking.BookingService.GetBooking:output_type -> booking.Booking
	2, // 10: booking.BookingService.GetUserBookings:output_type -> booking.GetUserBookingsResponse
	6, // 11: booking.BookingService.BookTickets:output_type -> booking.Booking
	5, // 12: booking.BookingService.CancelBooking:output_type -> booking.CancelBookingResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_grpc_proto_booking_proto_init() }
func file_api_grpc_proto_booking_proto_init() {
	if File_api_grpc_proto_booking_proto != nil {
		return
	}
	file_api_grpc_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_proto_booking_proto_rawDesc), len(file_api_grpc_proto_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_proto_booking_proto_goTypes,
		DependencyIndexes: file_api_grpc_proto_booking_proto_depIdxs,
		MessageInfos:      file_api_grpc_proto_booking_proto_msgTypes,
	}.Build()
	File_api_grpc_proto_booking_proto = out.File
	file_api_grpc_proto_booking_proto_goTypes = nil
	file_api_grpc_proto_booking_proto_depIdxs = nil
}
