// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/grpc/proto/concert.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConcertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConcertRequest) Reset() {
	*x = GetConcertRequest{}
	mi := &file_api_grpc_proto_concert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConcertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConcertRequest) ProtoMessage() {}

func (x *GetConcertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_concert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConcertRequest.ProtoReflect.Descriptor instead.
func (*GetConcertRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_concert_proto_rawDescGZIP(), []int{0}
}

func (x *GetConcertRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListConcertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Artist        string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Venue         string                 `protobuf:"bytes,4,opt,name=venue,proto3" json:"venue,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	DateFrom      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	AvailableOnly bool                   `protobuf:"varint,8,opt,name=available_only,json=availableOnly,proto3" json:"available_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConcertsRequest) Reset() {
	*x = ListConcertsRequest{}
	mi := &file_api_grpc_proto_concert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConcertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConcertsRequest) ProtoMessage() {}

func (x *ListConcertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_concert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConcertsRequest.ProtoReflect.Descriptor instead.
func (*ListConcertsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_concert_proto_rawDescGZIP(), []int{1}
}

func (x *ListConcertsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConcertsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConcertsRequest) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *ListConcertsRequest) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *ListConcertsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListConcertsRequest) GetDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *ListConcertsRequest) GetDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTo
	}
	return nil
}

func (x *ListConcertsRequest) GetAvailableOnly() bool {
	if x != nil {
		return x.AvailableOnly
	}
	return false
}

type ListConcertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Concerts      []*Concert             `protobuf:"bytes,1,rep,name=concerts,proto3" json:"concerts,omitempty"`
	Meta          *PaginationMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConcertsResponse) Reset() {
	*x = ListConcertsResponse{}
	mi := &file_api_grpc_proto_concert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConcertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConcertsResponse) ProtoMessage() {}

func (x *ListConcertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_concert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConcertsResponse.ProtoReflect.Descriptor instead.
func (*ListConcertsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_concert_proto_rawDescGZIP(), []int{2}
}

func (x *ListConcertsResponse) GetConcerts() []*Concert {
	if x != nil {
		return x.Concerts
	}
	return nil
}

func (x *ListConcertsResponse) GetMeta() *PaginationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CreateConcertRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Artist           string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Venue            string                 `protobuf:"bytes,3,opt,name=venue,proto3" json:"venue,omitempty"`
	ConcertDate      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=concert_date,json=concertDate,proto3" json:"concert_date,omitempty"`
	TotalTickets     int32                  `protobuf:"varint,5,opt,name=total_tickets,json=totalTickets,proto3" json:"total_tickets,omitempty"`
	Price            float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	BookingStartTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=booking_start_time,json=bookingStartTime,proto3" json:"booking_start_time,omitempty"`
	BookingEndTime   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=booking_end_time,json=bookingEndTime,proto3" json:"booking_end_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateConcertRequest) Reset() {
	*x = CreateConcertRequest{}
	mi := &file_api_grpc_proto_concert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConcertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConcertRequest) ProtoMessage() {}

func (x *CreateConcertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_concert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConcertRequest.ProtoReflect.Descriptor instead.
func (*CreateConcertRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_concert_proto_rawDescGZIP(), []int{3}
}

func (x *CreateConcertRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateConcertRequest) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *CreateConcertRequest) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *CreateConcertRequest) GetConcertDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ConcertDate
	}
	return nil
}

func (x *CreateConcertRequest) GetTotalTickets() int32 {
	if x != nil {
		return x.TotalTickets
	}
	return 0
}

func (x *CreateConcertRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateConcertRequest) GetBookingStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BookingStartTime
	}
	return nil
}

func (x *CreateConcertRequest) GetBookingEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BookingEndTime
	}
	return nil
}

type UpdateConcertRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Artist           string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Venue            string                 `protobuf:"bytes,4,opt,name=venue,proto3" json:"venue,omitempty"`
	ConcertDate      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=concert_date,json=concertDate,proto3" json:"concert_date,omitempty"`
	TotalTickets     int32                  `protobuf:"varint,6,opt,name=total_tickets,json=totalTickets,proto3" json:"total_tickets,omitempty"`
	Price            float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	BookingStartTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=booking_start_time,json=bookingStartTime,proto3" json:"booking_start_time,omitempty"`
	BookingEndTime   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=booking_end_time,json=bookingEndTime,proto3" json:"booking_end_time,omitempty"`
	Version          int32                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateConcertRequest) Reset() {
	*x = UpdateConcertRequest{}
	mi := &file_api_grpc_proto_concert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConcertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConcertRequest) ProtoMessage() {}

func (x *UpdateConcertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_concert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConcertRequest.ProtoReflect.Descriptor instead.
func (*UpdateConcertRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_concert_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateConcertRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateConcertRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateConcertRequest) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *UpdateConcertRequest) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *UpdateConcertRequest) GetConcertDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ConcertDate
	}
	return nil
}

func (x *UpdateConcertRequest) GetTotalTickets() int32 {
	if x != nil {
		return x.TotalTickets
	}
	return 0
}

func (x *UpdateConcertRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateConcertRequest) GetBookingStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BookingStartTime
	}
	return nil
}

func (x *UpdateConcertRequest) GetBookingEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BookingEndTime
	}
	return nil
}

func (x *UpdateConcertRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Concert struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Artist           string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Venue            string                 `protobuf:"bytes,4,opt,name=venue,proto3" json:"venue,omitempty"`
	ConcertDate      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=concert_date,json=concertDate,proto3" json:"concert_date,omitempty"`
	TotalTickets     int32                  `protobuf:"varint,6,opt,name=total_tickets,json=totalTickets,proto3" json:"total_tickets,omitempty"`
	AvailableTickets int32                  `protobuf:"varint,7,opt,name=available_tickets,json=availableTickets,proto3" json:"available_tickets,omitempty"`
	Price            float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	BookingStartTime *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=booking_start_time,json=bookingStartTime,proto3" json:"booking_start_time,omitempty"`
	BookingEndTime   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=booking_end_time,json=bookingEndTime,proto3" json:"booking_end_time,omitempty"`
	Version          int32                  `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Concert) Reset() {
	*x = Concert{}
	mi := &file_api_grpc_proto_concert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Concert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Concert) ProtoMessage() {}

func (x *Concert) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_concert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Concert.ProtoReflect.Descriptor instead.
func (*Concert) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_concert_proto_rawDescGZIP(), []int{5}
}

func (x *Concert) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Concert) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Concert) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Concert) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *Concert) GetConcertDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ConcertDate
	}
	return nil
}

func (x *Concert) GetTotalTickets() int32 {
	if x != nil {
		return x.TotalTickets
	}
	return 0
}

func (x *Concert) GetAvailableTickets() int32 {
	if x != nil {
		return x.AvailableTickets
	}
	return 0
}

func (x *Concert) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Concert) GetBookingStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BookingStartTime
	}
	return nil
}

func (x *Concert) GetBookingEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BookingEndTime
	}
	return nil
}

func (x *Concert) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Concert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Concert) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_grpc_proto_concert_proto protoreflect.FileDescriptor

const file_api_grpc_proto_concert_proto_rawDesc = "" +
	"\n" +
	"\x1capi/grpc/proto/concert.proto\x12\aconcert\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bapi/grpc/proto/common.proto\"#\n" +
	"\x11GetConcertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9d\x02\n" +
	"\x13ListConcertsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x14\n" +
	"\x05venue\x18\x04 \x01(\tR\x05venue\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x127\n" +
	"\tdate_from\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bdateFrom\x123\n" +
	"\adate_to\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06dateTo\x12%\n" +
	"\x0eavailable_only\x18\b \x01(\bR\ravailableOnly\"p\n" +
	"\x14ListConcertsResponse\x12,\n" +
	"\bconcerts\x18\x01 \x03(\v2\x10.concert.ConcertR\bconcerts\x12*\n" +
	"\x04meta\x18\x02 \x01(\v2\x16.common.PaginationMetaR\x04meta\"\xe2\x02\n" +
	"\x14CreateConcertRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artist\x12\x14\n" +
	"\x05venue\x18\x03 \x01(\tR\x05venue\x12=\n" +
	"\fconcert_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vconcertDate\x12#\n" +
	"\rtotal_tickets\x18\x05 \x01(\x05R\ftotalTickets\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12H\n" +
	"\x12booking_start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x10bookingStartTime\x12D\n" +
	"\x10booking_end_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0ebookingEndTime\"\x8c\x03\n" +
	"\x14UpdateConcertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x14\n" +
	"\x05venue\x18\x04 \x01(\tR\x05venue\x12=\n" +
	"\fconcert_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vconcertDate\x12#\n" +
	"\rtotal_tickets\x18\x06 \x01(\x05R\ftotalTickets\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12H\n" +
	"\x12booking_start_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x10bookingStartTime\x12D\n" +
	"\x10booking_end_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0ebookingEndTime\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x05R\aversion\"\xa2\x04\n" +
	"\aConcert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x14\n" +
	"\x05venue\x18\x04 \x01(\tR\x05venue\x12=\n" +
	"\fconcert_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vconcertDate\x12#\n" +
	"\rtotal_tickets\x18\x06 \x01(\x05R\ftotalTickets\x12+\n" +
	"\x11available_tickets\x18\a \x01(\x05R\x10availableTickets\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12H\n" +
	"\x12booking_start_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x10bookingStartTime\x12D\n" +
	"\x10booking_end_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0ebookingEndTime\x12\x18\n" +
	"\aversion\x18\v \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\x9d\x02\n" +
	"\x0eConcertService\x12:\n" +
	"\n" +
	"GetConcert\x12\x1a.concert.GetConcertRequest\x1a\x10.concert.Concert\x12K\n" +
	"\fListConcerts\x12\x1c.concert.ListConcertsRequest\x1a\x1d.concert.ListConcertsResponse\x12@\n" +
	"\rCreateConcert\x12\x1d.concert.CreateConcertRequest\x1a\x10.concert.Concert\x12@\n" +
	"\rUpdateConcert\x12\x1d.concert.UpdateConcertRequest\x1a\x10.concert.ConcertB#Z!concert-ticket-api/api/grpc/protob\x06proto3"

var (
	file_api_grpc_proto_concert_proto_rawDescOnce sync.Once
	file_api_grpc_proto_concert_proto_rawDescData []byte
)

func file_api_grpc_proto_concert_proto_rawDescGZIP() []byte {
	file_api_grpc_proto_concert_proto_rawDescOnce.Do(func() {
		file_api_grpc_proto_concert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_proto_concert_proto_rawDesc), len(file_api_grpc_proto_concert_proto_rawDesc)))
	})
	return file_api_grpc_proto_concert_proto_rawDescData
}

var file_api_grpc_proto_concert_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_grpc_proto_concert_proto_goTypes = []any{
	(*GetConcertRequest)(nil),     // 0: concert.GetConcertRequest
	(*ListConcertsRequest)(nil),   // 1: concert.ListConcertsRequest
	(*ListConcertsResponse)(nil),  // 2: concert.ListConcertsResponse
	(*CreateConcertRequest)(nil),  // 3: concert.CreateConcertRequest
	(*UpdateConcertRequest)(nil),  // 4: concert.UpdateConcertRequest
	(*Concert)(nil),               // 5: concert.Concert
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*PaginationMeta)(nil),        // 7: common.PaginationMeta
}
var file_api_grpc_proto_concert_proto_depIdxs = []int32{
	6,  // 0: concert.ListConcertsRequest.date_from:type_name -> google.protobuf.Timestamp
	6,  // 1: concert.ListConcertsRequest.date_to:type_name -> google.protobuf.Timestamp
	5,  // 2: concert.ListConcertsResponse.concerts:type_name -> concert.Concert
	7,  // 3: concert.ListConcertsResponse.meta:type_name -> common.PaginationMeta
	6,  // 4: concert.CreateConcertRequest.concert_date:type_name -> google.protobuf.Timestamp
	6,  // 5: concert.CreateConcertRequest.booking_start_time:type_name -> google.protobuf.Timestamp
	6,  // 6: concert.CreateConcertRequest.booking_end_time:type_name -> google.protobuf.Timestamp
	6,  // 7: concert.UpdateConcertRequest.concert_date:type_name -> google.protobuf.Timestamp
	6,  // 8: concert.UpdateConcertRequest.booking_start_time:type_name -> google.protobuf.Timestamp
	6,  // 9: concert.UpdateConcertRequest.booking_end_time:type_name -> google.protobuf.Timestamp
	6,  // 10: concert.Concert.concert_date:type_name -> google.protobuf.Timestamp
	6,  // 11: concert.Concert.booking_start_time:type_name -> google.protobuf.Timestamp
	6,  // 12: concert.Concert.booking_end_time:type_name -> google.protobuf.Timestamp
	6,  // 13: concert.Concert.created_at:type_name -> google.protobuf.Timestamp
	6,  // 14: concert.Concert.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 15: concert.ConcertService.GetConcert:input_type -> concert.GetConcertRequest
	1,  // 16: concert.ConcertService.ListConcerts:input_type -> concert.ListConcertsRequest
	3,  // 17: concert.ConcertService.CreateConcert:input_type -> concert.CreateConcertRequest
	4,  // 18: concert.ConcertService.UpdateConcert:input_type -> concert.UpdateConcertRequest
	5,  // 19: concert.ConcertService.GetConcert:output_type -> concert.Concert
	2,  // 20: concert.ConcertService.ListConcerts:output_type -> concert.ListConcertsResponse
	5,  // 21: concert.ConcertService.CreateConcert:output_type -> concert.Concert
	5,  // 22: concert.ConcertService.UpdateConcert:output_type -> concert.Concert
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_grpc_proto_concert_proto_init() }
func file_api_grpc_proto_concert_proto_init() {
	if File_api_grpc_proto_concert_proto != nil {
		return
	}
	file_api_grpc_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_proto_concert_proto_rawDesc), len(file_api_grpc_proto_concert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_proto_concert_proto_goTypes,
		DependencyIndexes: file_api_grpc_proto_concert_proto_depIdxs,
		MessageInfos:      file_api_grpc_proto_concert_proto_msgTypes,
	}.Build()
	File_api_grpc_proto_concert_proto = out.File
	file_api_grpc_proto_concert_proto_goTypes = nil
	file_api_grpc_proto_concert_proto_depIdxs = nil
}
